# Generated by Django 3.0.3 on 2020-03-27 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credits', '0002_auto_20200327_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditsPayed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credit',
            name='received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditsReceived', to=settings.AUTH_USER_MODEL),
        ),
    ]
