# Generated by Django 3.0.3 on 2020-03-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_auto_20200327_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='payed',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='received',
            new_name='receiver',
        ),
    ]
