# Generated by Django 3.0.3 on 2020-04-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_auto_20200327_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credit',
            new_name='credits',
        ),
    ]
