# Generated by Django 3.0.3 on 2020-04-09 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credits', '0005_auto_20200409_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credit',
            new_name='Credits',
        ),
    ]
