# Generated by Django 3.0.3 on 2020-04-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_auto_20200409_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
