# Generated by Django 3.0.3 on 2020-04-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_auto_20200409_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='receiver',
            new_name='ownerId',
        ),
        migrations.RenameField(
            model_name='credits',
            old_name='payer',
            new_name='teacherId',
        ),
    ]
