# Generated by Django 3.0.3 on 2020-04-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_auto_20200412_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='ownerId',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='credits',
            old_name='teacherId',
            new_name='teacher',
        ),
    ]
