# Generated by Django 3.0 on 2019-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=30, unique=True)),
                ('subject_en', models.CharField(db_index=True, max_length=30, null=True, unique=True)),
                ('subject_de', models.CharField(db_index=True, max_length=30, null=True, unique=True)),
            ],
        ),
    ]
