# Generated by Django 3.0 on 2019-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_es',
            field=models.CharField(db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
