# Generated by Django 3.0 on 2019-12-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20191218_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
