# Generated by Django 3.0 on 2019-12-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20191218_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_af',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ar',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ast',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_az',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_be',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_bg',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_bn',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_br',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_bs',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ca',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_cs',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_cy',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_da',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_de',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_dsb',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_el',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_en',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_en_au',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_en_gb',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_eo',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_es',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_es_ar',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_es_co',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_es_mx',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_es_ni',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_es_ve',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_et',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_eu',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_fa',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_fi',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_fr',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_fy',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ga',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_gd',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_gl',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_he',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_hi',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_hr',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_hsb',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_hu',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_hy',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ia',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ind',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_io',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_is',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_it',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ja',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ka',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_kab',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_kk',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_km',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_kn',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ko',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_lb',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_lt',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_lv',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_mk',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ml',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_mn',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_mr',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_my',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_nb',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ne',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_nl',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_nn',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_os',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_pa',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_pl',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_pt',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_pt_br',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ro',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sk',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sl',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sq',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sr',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sr_latn',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sv',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_sw',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ta',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_te',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_th',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_tr',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_tt',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_udm',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_uk',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_ur',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_uz',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_vi',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_zh_hans',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_zh_hant',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
