# Generated by Django 3.1.5 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20191218_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_ar_dz',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_ig',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_ky',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_tg',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_tk',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
