# Generated by Django 3.0.3 on 2020-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200212_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='readByRecipient',
            field=models.BooleanField(default=False),
        ),
    ]
