# Generated by Django 3.0.3 on 2020-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_readbyrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='readByRecipientTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
