# Generated by Django 3.0.3 on 2020-04-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_readbyrecipienttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='readByRecipientTime',
            new_name='time_read',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='readByRecipient',
        ),
    ]
