# Generated by Django 3.0.3 on 2020-07-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200417_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_notified',
            field=models.BooleanField(default=False),
        ),
    ]
