# Generated by Django 3.0 on 2019-12-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_subject_es'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherteaches',
            unique_together={('teacher', 'subject')},
        ),
    ]
