# Generated by Django 3.0.2 on 2020-02-17 02:17

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200217_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='price50m',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=19),
        ),
    ]
