# Generated by Django 3.0 on 2019-12-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='teacherConfirmed',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calevent',
            name='userConfirmed',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
