# Generated by Django 3.0 on 2019-12-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20191223_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calevent',
            old_name='booker',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='calevent',
            old_name='owner',
            new_name='teacher',
        ),
    ]
