# Generated by Django 3.0.2 on 2020-02-11 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20191223_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='videoConferenceId',
            field=models.TextField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
