# Generated by Django 3.0.2 on 2020-02-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_calevent_videoconferenceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='videoConferenceId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
