# Generated by Django 3.0.2 on 2020-02-14 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0007_auto_20200213_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_from', models.DateTimeField(db_index=True)),
                ('working_till', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_available_time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CalEvent',
            new_name='Lesson',
        ),
        migrations.DeleteModel(
            name='CalAvailableTime',
        ),
    ]
