# Generated by Django 3.0.2 on 2020-02-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20200214_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='working_till',
            field=models.DateTimeField(db_index=True),
        ),
    ]
