# Generated by Django 3.0 on 2019-12-15 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilePic', imagekit.models.fields.ProcessedImageField(upload_to=profiles.models.generate_profilePic_filename)),
                ('description_short', models.TextField(blank=True, help_text='Short description', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Long description', max_length=2500)),
                ('isTeacher', models.BooleanField(db_index=True, default=False, help_text='I am a teacher')),
            ],
        ),
    ]
