# Generated by Django 3.0.2 on 2020-01-31 00:11

from django.db import migrations
import imagekit.models.fields
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=imagekit.models.fields.ProcessedImageField(default='/static/img/noprofilepic.png', upload_to=profiles.models.generate_profilePic_filename),
        ),
    ]
