# Generated by Django 3.0.2 on 2020-01-31 00:31

from django.db import migrations
import imagekit.models.fields
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200131_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=imagekit.models.fields.ProcessedImageField(upload_to=profiles.models.generate_profilePic_filename),
        ),
    ]
