# Generated by Django 3.0.3 on 2020-06-16 23:49

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200505_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Berlin'),
            preserve_default=False,
        ),
    ]
